// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type DailyClick struct {
	ID     int64         `json:"id"`
	Slug   string        `json:"slug"`
	Day    time.Time     `json:"day"`
	Clicks sql.NullInt64 `json:"clicks"`
}

type Link struct {
	ID        int64          `json:"id"`
	Slug      string         `json:"slug"`
	Url       string         `json:"url"`
	User      sql.NullString `json:"user"`
	CreatedAt time.Time      `json:"created_at"`
	Clicks    sql.NullInt64  `json:"clicks"`
}
